### PR TITLE
Add keyPrefix

### PR DESCRIPTION
**Pull request by kiyasov**
To separate subscriptions from different sites.

Example

```
const pubsub = new RedisPubSub({
  keyPrefix: `${process.env.NODE_ENV}:${process.env.HOSTNAME}:`
});
```

### CODE REVIEW

**Comment by kiyasov** [comment]
@davidyaha

**Comment by davidyaha** [comment]
Hey @kiyasov, Thanks for the PR!

Would you mind explaining the use case you are supporting with this added feature?
I am a bit confused regarding the setup that's in play here and why this should not be handled on the library's user code.
Meaning - when you are subscribing and publishing to a certain trigger create the right trigger that is relevant for your setup.

Thanks again!

**Comment by kiyasov** [comment]
> Hey @kiyasov, Thanks for the PR!
> 
> Would you mind explaining the use case you are supporting with this added feature?
> I am a bit confused regarding the setup that's in play here and why this should not be handled on the library's user code.
> Meaning - when you are subscribing and publishing to a certain trigger create the right trigger that is relevant for your setup.
> 
> Thanks again!

Hi! The point is that this is very useful when multiple sites are running on the same code. Making a separate trigger for each site is not very good.

In another library under socket.io implemented the same way https://github.com/socketio/socket.io-redis/blob/master/lib/index.ts#L117

**Comment by davidyaha** [comment]
I think I missed your point.
Would you mind giving an example for such a need? maybe provide a code example where it shows how creating a trigger per site on your GraphQL resolvers poses an issue.

Thanks!

**Comment by kiyasov** [comment]
As an example, I have a newgame trigger. It sends data about a new game. Without the prefix, this trigger is sent to all sites that listen to it. A prefix would solve this problem. To send only to the desired site, as an example


This can of course be corrected by using unique trigger names, but this is not practical

image


> Думаю, я упустил вашу точку зрения.
> Не могли бы вы привести пример такой необходимости? возможно, предоставьте пример кода, в котором показано, как создание триггера для каждого сайта на ваших преобразователях GraphQL создает проблему.
> 
> Благодаря!

**Comment by davidyaha** [comment]
@kiyasov Okay yeah I can see why that can be useful. 
My main concern is that we might add an option that could "complicate the code" (in the sense that all additions complicate the code) where it could be easily fixed on your code as it has more context and the suggested change does create a unique trigger for each environment, just in the package code rather in your code.

Maybe consider creating a utility on you project that handles the env for you. For example: 
```js
const prefix = `${process.env.NODE_ENV}:${process.env.HOSTNAME}:`;
const createTriggerSubscribe = (triggerName, pubsub) => pubsub.asyncIterator(`${prefix}${triggerName}`);
const publishEventToTrigger = (triggerName, event) => pubsub.publish(`${prefix}${triggerName}`, event);
```

This will be used like so in your example:
```js
Subscription: {
  newGame: {
    subscribe: (root, args, { pubsub }) => createTriggerSubscribe("newGame", pubsub),
  }
}
```

Will that work?
Thanks again for your contribution.

**Pull request closed without merging**
