### PR TITLE
feat: support graphql subscriptions v3

### PR DESCRIPTION
**Pull request by williamrijksen**

### CODE REVIEW

**Comment by kasir-barati** [comment]
We already have changed the docs in NestJS: https://github.com/nestjs/docs.nestjs.com/pull/3150#issuecomment-2494600056

Any idea?

**Comment by kasir-barati** [comment]
BTW I also realized that right now when I use this code my type won't match anymore with Apollo server's auto geenrated code. Does this PR covers this topic as well?

Code: 
```ts
import { RedisPubSub } from 'graphql-redis-subscriptions';
import type { Resolvers } from '../../__generated__/resolvers-types';

const redisPubSub = new RedisPubSub();

  Subscription: {
    top: {
      subscribe(parent, args, context, info) {
        return redisPubSub.asyncIterator([
          'server-statistics-changed',
        ]);
      },
    }
  }
}
```

Error: 
```shell
Error msg: ` Type 'AsyncIterator<unknown, any, any>' is not assignable to type 'AsyncIterable<any> | Promise<AsyncIterable<any>>'.ts(2322)`
```

Code: english

**Comment by williamrijksen** [comment]
@davidyaha Can you please take a look at this pull request?

**Comment by davecusatis** [comment]
can we get this merged in please?

**Comment by davidyaha** [comment]
Thanks @williamrijksen for the contribution and sorry for the delay on my part.
I'll publish the new version asap.

**Comment by williamrijksen** [comment]
Thanks for releasing!

**Pull request merged**
