### PR TITLE
Redis Cluster to be used in types, Dependencies update ...

### PR DESCRIPTION
**Pull request by arsonik**

### CODE REVIEW

**Comment by davidyaha** [comment]
Hey @arsonik!
Thanks for the PR!

Could you please add a test to the integration tests so that I could confirm the API is used correctly across the library?
And if that works, I would love to see a section in the README that will notify people about the added support for Cluster.

Thanks ahead!

**Comment by arsonik** [comment]
Let me know what you think !

**Comment by davidyaha** [comment]
Hey @arsonik!
Thanks for the changes! It looks great!
One thing that I would like to add is a small change to the travis file so that we would be able to pass integrations tests on the CI.
Would you mind making that addition?
Alternatively, I can merge and do the changes myself.
Thanks ahead!

**Comment by arsonik** [comment]
Ok 
I think we are good now !?
Travis CI OK

- Migrated from tslint to eslint
- Migrated from old Istanbul to Nyc for coverage 
- Test using ts-node i/o compiled js files

**Review by davidyaha — APPROVED** [review]

**Comment by davidyaha** [comment]
Thanks @arsonik!!!
Will release a new version ASAP.

**Comment by davidyaha** [comment]
v2.3.0 is now available on NPM.
Thanks again!

**Comment by arsonik** [comment]
@davidyaha How come when I `yarn upgrade` from a private repo. 
I get the old code (dist), README and package show the new stuff not the compiled code !
cheers

**Comment by arsonik** [comment]
I found the issue ! 
Before: Test phase was executing `tsc` which was the published dist !
Now: Tests are done without compiling ts-node 

here is the fix
https://github.com/davidyaha/graphql-redis-subscriptions/pull/252

**Comment by davidyaha** [comment]
Yes I see, was an oversight on my end as well.
Will publish the compiled code right now and continue the conversation on #252 as I think we should maybe figure out a better way to handle the compile script.

**Comment by davidyaha** [comment]
v2.3.1 is available on NPM.

**Comment by arsonik** [comment]
Just updated and its working with the new compiled code

**Pull request merged**
